services:
  app:
    build: .
    container_name: auth-microservice-app
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
      # Mount the keys from your root directory into the container
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  seed-data:
    name: seed-data
  cron-output:
    name: cron-output